version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel-network

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "8001:80"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      - MYSQL_DATABASE=Laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  pma:
    image: phpmyadmin
    container_name: laravel-pma
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=laravel-mysql
      - UPLOAD_LIMIT=1000000000
    networks:
      - laravel-network
    depends_on:
      - db

networks:
  laravel-network:
    driver: bridge